export const BASE_URL = "https://jsonplaceholder.typicode.com";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_RESPONSE = "GET_POSTS_RESPONSE";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_RESPONSE = "GET_POST_RESPONSE";
export const GET_POST_ERROR = "GET_POST_ERROR";

export const GET_POST_COMMENTS_REQUEST = "GET_POST_COMMENTS_REQUEST";
export const GET_POST_COMMENTS_RESPONSE = "GET_POST_COMMENTS_RESPONSE";
export const GET_POST_COMMENTS_ERROR = "GET_POST_COMMENTS_ERROR";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_RESPONSE = "GET_USER_RESPONSE";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const LOAD_MORE_ITEMS = "LOAD_MORE_ITEMS";
